### ISSUE TITLE
Grappling get's stuck on player due to unbreaking enchant

### ISSUE THREAD

**Issue by Trigonomancer** [yyon/grapplemod#55] opened 2019-08-19 20:13 UTC
For some reason every time I fire my grappling hook it gets stuck on my player model, I tried a world log out/login and a game restart to no avail.

Video showcasing the issue:
https://youtu.be/Dz69cajWNfI

Update:
The problems seems to be caused by enchanting the hook with unbreaking.

Video:
https://youtu.be/TN40TdePV5E

**Comment by yyon** [comment] 2022-05-13 22:43
duplicate of #88

**Closed** 2022-05-13 22:44 UTC
Labels: duplicate
