### ISSUE TITLE
Server Crash - mc 1.10 - grapplemod v7 for 1.9.4

### ISSUE THREAD

**Issue by RogueShadow** [yyon/grapplemod#23] opened 2016-07-03 21:32 UTC
Wasn't sure if I should bother posting, was just seeing how it works in 1.10 and other mods. It crashes the server if you shoot the duel grappling hook into the sky and wait. On a multiplayer server.  Still investigating a bit if it can be prevented by using the gamerules I seen mentioned. Haven't tried it on the version it was meant for. Just a heads up I guess? 
[crash-2016-07-03_17.28.38-server.txt](https://github.com/yyon/grapplemod/files/345314/crash-2016-07-03_17.28.38-server.txt)

Tried it a few times, I must have been lucky, last time I couldn't get back on the server.  Just removed it for now.  Not really blaming you, since it's not the right version. Just seems to work fine so in 1.10 except for this.

**Comment by nitefang** [comment] 2016-09-29 16:19
I have had similar problems on my multiplayer server. A user used a standard hook and it crashed her client and then the server. When she tried to reconnect she crashed again. After that I actually removed the block limit I had put in place and she was able to rejoin. I have had other problems with client crashes though since then and have not be been able to find a solution.

**Comment by BBoldt** [comment] 2016-10-18 05:35
Anotha one:
https://unascribed.com/hcf/crash-2016-10-18_01.32.12-server.txt

**Comment by yyon** [comment] 2022-05-14 00:13
duplicate of #90

**Closed by yyon** 2022-05-14 00:13 UTC
