### ISSUE TITLE
Changing rope length is weird and buggy

### ISSUE THREAD

**Issue by JeffBobbo** [yyon/grapplemod#11] opened 2015-12-29 02:37 UTC
Changing rope length while suspended seems to work fine (even if the speed is quite fast).

When you're on the ground though, it seems trying to lengthen the rope doesn't do anything (or does it very slowly), trying to shorten it causes a weird jump up.

Video to help explain: http://dl.dropbox.com/u/14141289/boop.mp4 - 25s, 15MB

Mod infos:
MCP: 9.05
FML: 8.0.99.99
Minecraft Forge: 11.14.3.1450
Player API: 1.4
Smart Core: 1.2.1
grapplemod: 1.8-v3
Smart Moving: 16.2
Smart Render: 2.1

**Comment by JeffBobbo** [comment] 2015-12-30 22:25
Testing on fixes shows that this bug is from a conflict somewhere with Smart Moving as it's not present when Smart Moving isn't, not sure if it's fault of Smart Moving or your mod though (as well as the high speed of the rope length change).

Updated mod infos:
MCP: 9.05
FML: 8.0.99.99
Minecraft Forge: 11.14.3.1563
**Player API: 1.4**
**Smart Core: 1.2.1**
grapplemod: 1.8-v3
**Smart Moving: 16.2**
**Smart Render: 2.1**

**Comment by yyon** [comment] 2015-12-30 22:27
Is this not fixed in version 4? It seemed to work for me.

**Comment by JeffBobbo** [comment] 2015-12-30 22:31
It is (tested with just v4), just not when Smart Moving is loaded too; hence putting the smart moving mods in bold.

**Comment by yyon** [comment] 2015-12-31 20:17
I can't reproduce.

Mod info:
MCP: 9.05
FML: 8.0.99.99
Minecraft Forge: 11.14.4.1563
Player API: 1.4
Smart Core: 1.2.1
grapplemod: 1.8-v4
Smart Moving: 16.2
Smart Render: 2.1

**Closed** 2022-05-14 00:22 UTC
