### ISSUE TITLE
Leaving the world while using the grapple hook, if in multiplayer, will crash upon rejoining

### ISSUE THREAD

**Issue by pneumahub** [yyon/grapplemod#86] opened 2022-01-20 02:04 UTC
Hello, I am unable to rejoin my friends SMP server that is using the Create: Above and beyond modpack. I had to leave, so I used my grapple to get to a safe place then leave, however upon rejoining I am greeted with a crash. Here's the crash log:
https://crashy.net/JxQ9lTKyy7Ni4ooygBFg

Problem is the Grapple entity is NULL.

**Comment by Cyphecx** [comment] 2022-01-24 21:06
There is a similiar issue for single player. If you join a world and then leave, trying to join another world will crash the game. In this case, once you load the game up again, you are able to join the world without issue. At least until you leave again.

**Comment by yyon** [comment] 2022-05-13 22:23
Duplicate of #90

**Closed** 2022-05-13 22:44 UTC
Labels: duplicate
