### ISSUE TITLE
Ticking entity crash when using hook 1.12

### ISSUE THREAD

**Issue by Balgias** [yyon/grapplemod#68] opened 2020-11-29 03:53 UTC
My friends keep consistently crashing when using the grappling hook to get to them from a distance of a few hundred blocks away.

[crash-2020-11-28_22.50.13-client.txt](https://github.com/yyon/grapplemod/files/5611617/crash-2020-11-28_22.50.13-client.txt)

**Comment by pneumahub** [comment] 2022-01-20 02:07
I am currently having this same crash. Did you ever find a solution?

**Comment by yyon** [comment] 2022-05-13 22:30
duplicate of #90

**Closed** 2022-05-13 22:44 UTC
Labels: duplicate
