### ISSUE TITLE
[BUG] Mod not working in version 1.20.1

### ISSUE THREAD

**Issue by octo-1008** [yyon/grapplemod#126] opened 2023-12-28 13:25 UTC
The grapple hooks arent working with only the mod and cloth config in the mod folder
![image](https://github.com/yyon/grapplemod/assets/65249870/d5adc880-a645-444a-b4f7-3f4a67f46535)

Ender Staff still works

**Comment by Nyfaria** [comment] 2023-12-28 15:26
#121 duplicate, issue is resolved by downgrading to forge 47.1.3

**Closed as completed by Nyfaria** 2023-12-28 15:26 UTC
Labels: bug

**Comment by BeckPhillips** [comment] 2024-04-07 02:45
I think that the solution of "downgrade" isn't a great one, since some other mods might require a specific version of forge.
Are there any plans to figure out what the issue is and/or fix the problem?
